version: '3'
services:
  db:
    container_name: ${CONTAINER_PREFIX}_db
    image: 'postgres:12'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5433:5432'


  nginx:
    image: nginx
    container_name: ${CONTAINER_PREFIX}_web_server
    ports:
      - 80:80
    volumes:
      - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
    restart: unless-stopped
    depends_on:
      - app

  app:
    container_name: ${CONTAINER_PREFIX}_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./file_uploader:/app/file_uploader
      - ./scripts:/app/scripts
      - ./static:/app/static
      - ./data:/app/data
    ports:
      - '8000:8000'
    depends_on:
      - db



