# Generated by Django 3.1.1 on 2020-09-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20200906_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='reference',
            new_name='link',
        ),
    ]
